### ISSUE TITLE
Catalogue - Recherche avancée

### ISSUE THREAD

**Issue by ADefays** [SPW-DIG/Metawal-UX#1]
- [ ] Réfléchir aux filtres pertinents -> limiter le nombre de filtre à 7 (ex: la région géographique n'est pas pertinente puisque la plupart des fiches couvre la Wallonie)
![editeur_catalogue_recherche avancee_2](https://cloud.githubusercontent.com/assets/17477505/13354944/47c07c1e-dc9e-11e5-85c9-2457a547b8f7.png)

**Comment by vbombaerts** [comment]
* Type de ressource (hiérarchique) - ex : géodonnée, service de téléchargement, géodonnée raster, série temporelle de géodonnées...
* Thème du géoportail (hiérarchique) - ex : thème société et activités, sous-thème air 
* Contact pour la ressource (hiérarchique + rôles) - ex : les ressources dont le SPW est propriétaire, les ressources dont la DGO3 est gestionnaire, les ressources pour lesquelles la DIG est distributrice...
* Type de licence - ex : open data, accessibles au pouvoirs publics, OK pour utilisation commerciale...
* Echelle
* Année

A affiner avec les utilisateurs...

**Comment by ADefays** [comment]
Ok -> implémenté dans la v4
