### ISSUE TITLE
Nouvelle fiche - Step 1 - Aide au survol - Choix du type de ressource

### ISSUE THREAD

**Issue by ADefays** [SPW-DIG/Metawal-UX#3]
Réfléchir à une description pour chaque type de ressource. Cette information sera affichée au survol et doit donc être une description courte et simple.
-> je te joins un fichier excel où tu pourras compléter ces descriptions. L'urgence étant la description des 6 premiers.

[Description des types de ressources.xlsx](https://github.com/SPW-DIG/Metawal-UX/files/150559/Description.des.types.de.ressources.xlsx)

![editeur_creer sans import_step1](https://cloud.githubusercontent.com/assets/17477505/13389526/f5f44aaa-dec8-11e5-9266-633d4ba1d4dd.png)

**Comment by vbombaerts** [comment]
Voir fichier attaché Excel, onglet 2.
[Metawal et les types de ressources.xlsx](https://github.com/SPW-DIG/Metawal-UX/files/172189/Metawal.et.les.types.de.ressources.xlsx)
Egalement, j'ai essayé d'organiser ça dans une carte mentale.
![ressources](https://cloud.githubusercontent.com/assets/6093597/13748722/4bfffc88-e9fe-11e5-8760-b8cc0e3f7754.png)

**Comment by ADefays** [comment]
Parfait!!! Bien reçu!
Merci beaucoup.
J'implémente cela dans le proto v4.
