### ISSUE TITLE
Nouvelle fiche - Step 1 - Aide sous forme de question - Choix du type de ressource

### ISSUE THREAD

**Issue by ADefays** [SPW-DIG/Metawal-UX#5]
Réfléchir à un arbre décisionnel pour guider l'utilisateur à choisir la bonne ressource.
J'ai imaginé l'arbre suivant, mais c'est bien entendu un premier jet, mais juste pour que tu aies une idée du processus de guidage sous forme de questions que j'imagine.
Selon cet arbre, on pourrait, en maximum 5 questions, guider l'utilisateur vers la ressource adéquate. Qu'en penses-tu?

![guidage type de ressource_good](https://cloud.githubusercontent.com/assets/17477505/13422253/d216c61e-df93-11e5-89c3-e4ffee28038c.png)

**Comment by ADefays** [comment]
Il reste encore 2 ressources à catégoriser....

**Comment by vbombaerts** [comment]
Voici ma proposition. Projet de carte et levés de terrain topo sont anecdotiques pour le moment. Je propose qu'on laisse tomber.
![wf type de ressource](https://cloud.githubusercontent.com/assets/6093597/13748578/b46f6048-e9fd-11e5-9cfe-4ab2e6f085af.png)
A mettre en lien avec les définitions du #3

**Comment by ADefays** [comment]
OK -> Implémenté dans la version 4 du proto
