### ISSUE TITLE
Nouvelle fiche - Step 2 - Critères de qualité

### ISSUE THREAD

**Issue by ADefays** [SPW-DIG/Metawal-UX#6]
Faire la liste des critères de qualité.

- [ ] échelle de référence

- [ ] résolution spatiale

- [ ] précision X, Y

- [ ] précision Z
....

**Comment by vbombaerts** [comment]
- Echelle de référence ou/et résolution spatiale
- Mise à jour : date de dernière mise à jour, fréquence et informations sur la mise à jour (texte)
- Précision planimétrique et altimétrique
- Généalogie
- Test de conformité 
- Rapport de performance ou de qualité
- Autre mesure de qualité : ici on peut imaginer un wizard qui ouvre la porte à de nombreuses possibilités (les mesures de qualité prévue par l'ISO ou tout autre document)

**Comment by ADefays** [comment]
L'échelle de référence est la mesure de qualité proposée par défaut. L'utilisateur peut en ajouter d'autres via une pop-up. 

Le rapport de performance peut désormais être ajouté.

L'utilisateur peut également indiqué si un test de conformité a eu lieu ou pas.

Les dates de mises à jour ainsi que la généalogie se trouve dans l'onglet "description de la ressource".
